export const ProColumn = [
  { prop: "xh", label: "序号", width: 100 },
  { prop: "cpmc", label: "产品名称", width: 200 },
  { prop: "jcxm", label: "检测项目", width: 200 },
  { prop: "jcbz", label: "检测标准", width: 300 },
  { prop: "cnas", label: "CNAS资质", width: 100 },
  { prop: "cma", label: "CMA资质", width: 100 },
  { prop: "gys", label: "供应商名称", width: 250 },
  { prop: "tel", label: "联系电话", width: 150 },
  { prop: "city", label: "城市", width: 100 },
  { prop: "bz", label: "报价", width: 100 },
  { prop: "cb", label: "成本", width: 100 },
  { prop: "jcx", label: "检出限", width: 200 },
  { prop: "pdbz", label: "判定标准", width: 200 },
  { prop: "ypxq", label: "样品需求", width: 200 },
  { prop: "zxypl", label: "最小样品量", width: 200 },
  { prop: "csyq", label: "测试仪器实验方法", width: 200 },
  { prop: "zqlx", label: "周期类型", width: 200 },
  { prop: "jczq", label: "检测周期", width: 100 },
  { prop: "jdxz", label: "接单须知", width: 100 },
  { prop: "sfzy", label: "是否制样", width: 100 },
  { prop: "zyzq", label: "制样周期", width: 100 },
  { prop: "ztfy", label: "制样费用", width: 100 },
];
