export const ProColumn = [
  { prop: "xh", label: "序号", width: 100 },
  { prop: "title", label: "产品名称", width: 200 },
  { prop: "xm", label: "检测项目", width: 200 },
  { prop: "bz", label: "检测标准", width: 300 },
  { prop: "cnas", label: "CNAS资质", width: 100 },
  { prop: "cma", label: "CMA资质", width: 100 },
  { prop: "gys", label: "供应商名称", width: 250 },
  { prop: "tel", label: "联系电话", width: 150 },
  { prop: "city", label: "城市", width: 100 },
  { prop: "price", label: "报价", width: 100 },
  { prop: "oprice", label: "成本", width: 100 },
  { prop: "jc", label: "检出限", width: 200 },
  { prop: "pdbz", label: "判定标准", width: 200 },
  { prop: "ypxq", label: "样品需求", width: 200 },
  { prop: "zxyp", label: "最小样品量", width: 200 },
  { prop: "testway", label: "测试仪器实验方法", width: 200 },
  { prop: "zhouqitype", label: "周期类型", width: 200 },
  { prop: "jiancezhouqi", label: "检测周期", width: 100 },
  { prop: "xuzhi", label: "接单须知", width: 100 },
  { prop: "istest", label: "是否制样", width: 100 },
  { prop: "zhiyangzhouqi", label: "制样周期", width: 100 },
  { prop: "zhuyangfei", label: "制样费用", width: 100 },
];
