/*
 * @Author: Cram
 * @Date: 2022-06-27 17:39:56
 */
export const ProColumn = [
  { prop: "xh", label: "序号", width: 80 },
  { prop: "lb", label: "类别", width: 100 },
  { prop: "cpmc", label: "产品名称", width: 150 },
  { prop: "jcxm", label: "检测项目", width: 250 },
  { prop: "xmbm", label: "项目别名", width: 150 },
  { prop: "jcbz", label: "检测标准", width: 150 },
  { prop: "bzmc", label: "标准名称", width: 150 },
  { prop: "jcx", label: "检出限", width: 150 },
  { prop: "pdbz", label: "判定标准", width: 150 },
  { prop: "ypxq", label: "样品需求", width: 150 },
  { prop: "zxypl", label: "最小样品量", width: 150 },
  { prop: "csyq", label: "测试仪器实验方法", width: 150 },
  { prop: "zqlx", label: "周期类型", width: 150 },
  { prop: "jczq", label: "检测周期", width: 150 },
  { prop: "bz", label: "报价", width: 100 },
  { prop: "cb", label: "成本", width: 100 },
  { prop: "cma", label: "CMA资质", width: 100 },
  { prop: "cnas", label: "CNAS资质", width: 100 },
  { prop: "jdxz", label: "接单须知", width: 150 },
  { prop: "gys", label: "供应商名称", width: 250 },
  { prop: "sfzy", label: "是否制样", width: 100 },
  { prop: "zyzq", label: "制样周期", width: 150 },
  { prop: "ztfy", label: "制样费用", width: 150 },
];

export const typeOptions = [
  { value: "产品类" },
  { value: "声学" },
  { value: "阻燃" },
  { value: "塑料" },
  { value: "橡胶" },
  { value: "金属" },
  { value: "纺织品" },
  { value: "可靠性" },
  { value: "化学" },
  { value: "建材" },
  { value: "涂层镀层" },
  { value: "包装" },
  { value: "食品" },
  { value: "食品接触材料" },
  { value: "油品" },
  { value: "杂项" },
  { value: "轻工" },
  { value: "轻工产品" },
  { value: "半导体" },
  { value: "化妆品" },
  { value: "电工电子" },
  { value: "电线电缆" },
];
